# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "atesa_v2/tests"  # ignore folder and all its contents
  - "atesa_v2/_version.py"
  - "devtools"
  - "atesa_v2.egg-info"
  - "docs"
  - "setup.py"
  - "versioneer.py"
  - "atesa_v2/input_files"
  - "atesa_v2/templates"
  - "atesa_v2/temp.*"
  - "atesa_v2/.*temp"
